version: '2'
services:
  web:
    depends_on:
      - "demomongo-mongodb"
    network_mode: "host"
    build: .
    ports:
      - "9081:9081"
  demomongo-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
