apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-admin
  labels:
    app: spring-boot-admin
spec:
  selector:
    matchLabels:
      app: spring-boot-admin
  template:
    metadata:
      labels:
        app: spring-boot-admin
    spec:
      hostNetwork: true
      containers:
        - name: spring-boot-admin
          image: spring-boot-admin-image
          env:
            - name: ENV
              value: dev
            - name: JAVA_OPTS
              value: >-
                -Duser.timezone=America/Sao_Paulo -Dfile.encoding=UTF8 -Xms512m -Xmx512m
            - name: ENV_SBA_ACTIVE
              value: 'true'

