server:
  port: ${ENV_PORT:9082}
  servlet:
    context-path: ${ENV_CTX_PATH:/sample-tilt-2}
spring:
  profiles:
    active: ${ENV:dev}
  config:
    use-legacy-processing: true
  application:
    name: sample-tilt-2
  boot:
    admin:
      client:
        url: ${ENV_SBA_BASE_URL:http://localhost:9080/sba}
        username: admin
        password: admin
        enabled: ${ENV_SBA_ACTIVE:false}
        instance:
          name: ${spring.application.name}
          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
  endpoint:
    health:
      show-details: always