server:
  port: ${ENV_PORT:9082}
  servlet:
    context-path: ${ENV_CTX_PATH:/sample-tilt-2}
spring:
  profiles:
    active: ${ENV:dev}
  config:
    use-legacy-processing: true
  application:
    name: sample-tilt-2

