server:
  port: ${ENV_PORT:9081}
  servlet:
    context-path: ${ENV_CTX_PATH:/sample-tilt-1}
spring:
  profiles:
    active: ${ENV:dev}
  config:
    use-legacy-processing: true
  application:
    name: sample-tilt-1
  boot:
    admin:
      client:
        url: ${ENV_SBA_BASE_URL:http://localhost:9080/sba}
        username: admin
        password: admin
        enabled: ${ENV_SBA_ACTIVE:false}
        instance:
          name: ${spring.application.name}
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
  endpoint:
    health:
      show-details: always

sample2:
  host: http://localhost:9082/sample-tilt-2
http:
  timeout: ${ENV_HTTP_TIMEOUT:10}
  debug: ${ENV_HTTP_DEBUG:true}



